from ctypes.wintypes import HANDLE



MAX_PATH = 260

FILE_SHARE_READ   = 1  
FILE_SHARE_WRITE  = 2  
FILE_SHARE_DELETE = 4 

CREATE_NEW        = 1
CREATE_ALWAYS     = 2
OPEN_EXISTING     = 3
OPEN_ALWAYS       = 4
TRUNCATE_EXISTING = 5

FILE_ATTRIBUTE_READONLY              = 0x00000001  
FILE_ATTRIBUTE_HIDDEN                = 0x00000002  
FILE_ATTRIBUTE_SYSTEM                = 0x00000004  
FILE_ATTRIBUTE_DIRECTORY             = 0x00000010  
FILE_ATTRIBUTE_ARCHIVE               = 0x00000020  
FILE_ATTRIBUTE_DEVICE                = 0x00000040  
FILE_ATTRIBUTE_NORMAL                = 0x00000080  
FILE_ATTRIBUTE_TEMPORARY             = 0x00000100  
FILE_ATTRIBUTE_SPARSE_FILE           = 0x00000200  
FILE_ATTRIBUTE_REPARSE_POINT         = 0x00000400  
FILE_ATTRIBUTE_COMPRESSED            = 0x00000800  
FILE_ATTRIBUTE_OFFLINE               = 0x00001000  
FILE_ATTRIBUTE_NOT_CONTENT_INDEXED   = 0x00002000  
FILE_ATTRIBUTE_ENCRYPTED             = 0x00004000  
FILE_ATTRIBUTE_INTEGRITY_STREAM      = 0x00008000  
FILE_ATTRIBUTE_VIRTUAL               = 0x00010000  
FILE_ATTRIBUTE_NO_SCRUB_DATA         = 0x00020000  
FILE_ATTRIBUTE_EA                    = 0x00040000  
FILE_ATTRIBUTE_PINNED                = 0x00080000  
FILE_ATTRIBUTE_UNPINNED              = 0x00100000  
FILE_ATTRIBUTE_RECALL_ON_OPEN        = 0x00040000  
FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS = 0x00400000  
FILE_ATTRIBUTE_STRICTLY_SEQUENTIAL   = 0x20000000  

IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS = 0x560000  # TODO: build from other consts
IOCTL_STORAGE_QUERY_PROPERTY         = 0x2d1400  # TODO: build from other consts  

INVALID_HANDLE_VALUE = HANDLE(-1).value



__all__ = [
    'MAX_PATH',
    'FILE_SHARE_READ',
    'FILE_SHARE_WRITE',
    'FILE_SHARE_DELETE',
    'CREATE_NEW',
    'CREATE_ALWAYS',
    'OPEN_EXISTING',
    'OPEN_ALWAYS',
    'TRUNCATE_EXISTING',
    'FILE_ATTRIBUTE_READONLY',
    'FILE_ATTRIBUTE_HIDDEN',
    'FILE_ATTRIBUTE_SYSTEM',
    'FILE_ATTRIBUTE_DIRECTORY',
    'FILE_ATTRIBUTE_ARCHIVE',
    'FILE_ATTRIBUTE_DEVICE',
    'FILE_ATTRIBUTE_NORMAL',
    'FILE_ATTRIBUTE_TEMPORARY',
    'FILE_ATTRIBUTE_SPARSE_FILE',
    'FILE_ATTRIBUTE_REPARSE_POINT',
    'FILE_ATTRIBUTE_COMPRESSED',
    'FILE_ATTRIBUTE_OFFLINE',
    'FILE_ATTRIBUTE_NOT_CONTENT_INDEXED',
    'FILE_ATTRIBUTE_ENCRYPTED',
    'FILE_ATTRIBUTE_INTEGRITY_STREAM',
    'FILE_ATTRIBUTE_VIRTUAL',
    'FILE_ATTRIBUTE_NO_SCRUB_DATA',
    'FILE_ATTRIBUTE_EA',
    'FILE_ATTRIBUTE_PINNED',
    'FILE_ATTRIBUTE_UNPINNED',
    'FILE_ATTRIBUTE_RECALL_ON_OPEN',
    'FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS',
    'FILE_ATTRIBUTE_STRICTLY_SEQUENTIAL',
    'IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS',
    'IOCTL_STORAGE_QUERY_PROPERTY',
    'INVALID_HANDLE_VALUE',
]